### ISSUE TITLE
Pros/Cons PHP

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#10]
Purpose: Review the pros/cons of PHP in order to speak to them within tech discussion.

**Comment by colinmurphy01** [comment]
@heymatthenry interested in doing a 30 min primer next week on this for the team?

**Comment by heymatthenry** [comment]
Totally! Feel free to slot it in whenever and I'll be ready to go.

**Comment by colinmurphy01** [comment]
Scheduled for Thursday (30 mi).
