### ISSUE TITLE
Information Architecture Stress Test

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#102]
As an ```18F lead```, I want to ```pressure test our IA through DTMO and have them run critical/common use cases through it``` to see ```if the IA holds up and is properly organized.```

**Comment by thebestsophist** [comment]
https://app.mural.co/t/gsa6/m/gsa6/1573147671239/de1a28d984b99f14254b475375967cc5bec61347

- [x] tested with DTMO!
- [ ] content modeling

**Comment by colinmurphy01** [comment]
Were you able to schedule a meeting with members of Margaret's team?
