### ISSUE TITLE
JTR XML Editor | JTR Transition Recommendation

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#116]
## Story + Context
As a ```JTR Lead within DTMO``` I want ```an easy to use an XML editor to author changes and submit for review/approval``` in order to ```maintain the web version as our primary deliverable.```

## Success Criteria
- Plan A: WYSIWYG + XML editor with HTML/USWDS styling capabilities
- Plan B: Raw XML editor

**Comment by thebestsophist** [comment]
testing out things from this thread: https://gsa-tts.slack.com/archives/CC3JFT79N/p1575037972004700

**Comment by colinmurphy01** [comment]
@heymatthenry adding a note that you discussed eRegs use case and if they have an XML editor to recommend (which they don't).

@thebestsophist recommended a follow up to see if they have a rec from the OMB use case.
