### ISSUE TITLE
Un-Archive the Repo

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#17]
Contact #Github-admins to unarchive the repo.
https://github.com/18F/dtmo-jtr-prototype

**Comment by heymatthenry** [comment]
DTMO's [fork](https://github.com/defense-travel-management-office/dtmo-jtr-prototype) of the prototype repo is active, and the build is [live on Federalist](https://federalist-proxy.app.cloud.gov/site/defense-travel-management-office/dtmo-jtr-prototype/).
