### ISSUE TITLE
Get Write Access to JTR DTMO Repo

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#19]

**Comment by colinmurphy01** [comment]
@heymatthenry were you able to get write access to this? If not, I can follow up.

**Comment by heymatthenry** [comment]
My-Ly let me know she is working on it. No need to follow up just yet.

**Comment by heymatthenry** [comment]
That wasn't part of my initial message, so I did add a note about that. What I was asking about before was just getting access to the existing DTMO site's codebase which isn't in Github.

**Comment by heymatthenry** [comment]
Looks like I'm in there now.
