### ISSUE TITLE
Retro / Hopes + Fears Summary

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#21]
Purpose: Synthesize themes and tactical recommendations from the PA Retro + Hopes/Fears exercises, in order to be mindful of them in this exercise.

[Post It Notes from Workshop](https://app.mural.co/t/gsa6/m/gsa6/1570710401663/725bb59c4fde5246e624d708aabcb68a37b4811b)

Output Consideration: 
[Team Charter Section](https://docs.google.com/document/d/1Jsy6qIJu34YZoV_zMg9UBtUdkAZBf_s_T-QKGw3Zngw/edit#heading=h.jl3j4vv7aq89)

**Comment by MKathrynC** [comment]
will get to this early next week!

**Comment by MKathrynC** [comment]
https://docs.google.com/document/d/1gDjFLLlS1SHSdG-deKkyk5TE2pKFGrCSEtnv6u0HsOk/edit
