### ISSUE TITLE
Script / Intro Copy to Traveler

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#29]
Needs to be approved by Betsey.

**Comment by shawnique** [comment]
[DTMO Draft Email Script](https://docs.google.com/document/d/1Ksaf6fl7wGgh0HK8-rvdmGcvZrHA0t6fY5UU47rUKbo/edit#)

**Comment by colinmurphy01** [comment]
Edits Suggested in Google Docs. Feel free to review and consider them.

Then let's get them over to Betsey for suggestions and/or approval.
