### ISSUE TITLE
System Diagram | Per Diem Calculator

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#33]

**Comment by heymatthenry** [comment]
Started to sketch out the system but got excited about URLs first:
![Untitled (Draft)-2.jpg](https://images.zenhubusercontent.com/5d8a69c90d75970001f887d0/077ab222-8990-473c-9f48-63c64aa36d76)

**Comment by heymatthenry** [comment]
Pardon my novice Muraling but [this](https://app.mural.co/t/gsa6/m/gsa6/1571342146881/8e342b600ac21868d5fa9cd28bbb718c66224257) is the basic idea of how the calculator APIs should work, I think. ![f2fe3980-5070-47bf-9543-4893ee0bc79c.png](https://images.zenhubusercontent.com/5d8a69c90d75970001f887d0/2965af3c-e905-402d-ac3a-09283e8fdfdc)

**Comment by colinmurphy01** [comment]
Any thoughts on managing permissions/access?

Based on your diagram and the fact that DTMO houses the flat files on the site, I assume this is a public endpoint?

**Comment by heymatthenry** [comment]
None of the API endpoints here are behind authentication since they're all for the public site. That's not to say that the back-end data is exposed—just whatever comes through the API.
