### ISSUE TITLE
ATO Evaluation

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#36]
Have a conversation about the use of:
- Federalist
- Cloud.gov
- Static Files + SFTP or APIs

In the future we may want to test these tools in production as "beta" versions of their live counterparts - so get an assessment of what we might need to do to execute that.

**Comment by heymatthenry** [comment]
Raised issue with DTMO team 10/16

**Comment by colinmurphy01** [comment]
Scheduled Tuesday Morning!

**Comment by colinmurphy01** [comment]
• Waiting on Internal Meeting
• Then meeting with DMDS

**Comment by colinmurphy01** [comment]
Received written confirmation that DTMO will pursue an ATO for Federalist and will work with DMDC on running a proper evaluation.
