### ISSUE TITLE
Workshop Materials

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#4]
Workshop Materials:
- [x] Post It's 
- [x] Markers
- [ ] Projection/Connectors

**Comment by thebestsophist** [comment]
If i remember right, their conference rooms are set up with huge TVs and HDMI

**Comment by colinmurphy01** [comment]
@thebestsophist you saved the day for us with your travel pack. 

Do we need to file a compensation voucher so you can re-up your supplies? Also I want one, does 18F pay for it or do I need to fork over personal funds?
