### ISSUE TITLE
High-level content inventory of DTMO content streams

### ISSUE THREAD

**Issue by thebestsophist** [18F/dtmo-ei#64]
Importing from the excel doc inventories from BG

- [x] import excel docs into airtable
- [ ] tagging with users and topics

**Comment by thebestsophist** [comment]
Finished importing, now tagging

**Comment by colinmurphy01** [comment]
Imported!
Taggin Shit!

**Comment by colinmurphy01** [comment]
Note for Betsey, Nancy, Elizaebth – Updated pdfs / powerpoints or links to them.

**Comment by colinmurphy01** [comment]
Should be unblocked by Tuesday.

**Comment by thebestsophist** [comment]
Looks like new file from Romael works! will replace the data in the airtable today

**Comment by thebestsophist** [comment]
Dividing up with DTMO Strategic coms team!

**Comment by colinmurphy01** [comment]
Update from Betsey – this work should be ideally completed by EOD tomorrow.

**Comment by colinmurphy01** [comment]
Thursday Afternoon – QA by Cordelia?
