### ISSUE TITLE
Review Current Brand Guidelines | DTMO Styling

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#71]
## Story + Context
As a ```Project Lead``` I want to ```see if guidelines exist``` in order to ```align and repurpose in this new styling update```.

**Comment by copywritepaste** [comment]
I just wanted to clarify; DTMO does not actually have official/proper brand guidelines currently, there is only a handful of templates and assets that are used somewhat inconsistently. If other work hinges on a DTMO branding document, you will be waiting for Godot.
