### ISSUE TITLE
PO briefing deck

### ISSUE THREAD

**Issue by MKathrynC** [18F/dtmo-ei#84]
• Their current state as an org – where there are enablers and blockers to success
• The need for this role
• Outline the responsibilities and measures for success
• Outline the resources needed to properly support that person

**Comment by colinmurphy01** [comment]
Materials for Onsite can be viewed here: https://drive.google.com/open?id=1ba9N60Sy8kG9Iuoa4UXKA3cfKEp5e_lF

• Alignment Deck (Check-In + Case for PO)
• Role and Responsibilities of a PO + Transition Plan
