### ISSUE TITLE
Contact Audit Tagging Framework | Guided Support

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#89]
We want to create a centralized DB of contacts across all Tiers of Help and tag them based on ability to help with a problem/situation.

Success Criteria:
• 18F will create the columns: https://airtable.com/tblPhXkHzwzTsADjX/viw8Q97DJKclUseJU?blocks=hide
• DTMO will fill with DHRA/DTMO contacts
• 18F/DTMO will QA categorization tagging structure
• DTMO will provide expanded list of contacts
     • Local Data – https://drive.google.com/open?id=1e-DK5F9Txi2Fjd_Sg2zFzI5v9Ir_zDMJ

**Comment by thebestsophist** [comment]
[Invite link](https://airtable.com/invite/l?inviteId=invn2SZpKK9vmmkcx&inviteToken=a3743033997e50a7d60899a766135879e78bba9266e19612b9949b55775b6317) for @gsa.gov email addresses
